version: '3.7'

services:
  mariadb-blog:
    image: mariadb:latest
    ports: 
      - 26620:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_PASSWORD=&{DATABASE_PASSWORD}
      - MYSQL_USER=&{DATABASE_USER}
      - MYSQL_DATABASE=${DATABASE_NAME}
    restart: unless-stopped
