version: '3.7'

services:
  mariadb-blog:
    image: mariadb:latest
    ports: 
      - 26620:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_PASSWORD=&{DATABASE_PASSWORD}
      - MYSQL_USER=&{DATABASE_USER}
      - MYSQL_DATABASE=${DATABASE_NAME}
    restart: unless-stopped

  blog-backend:
    build:
      context: ./blog-backend
      dockerfile: Dockerfile
      target: base
    container_name: blog-backend
    ports:
     - 26621:3000
    command: npm run start:prod
    depends_on:
      - mariadb-blog
    restart: unless-stopped
